language: generic

branches:
  only:
  - master

before_install:
 - sudo apt-get install python-pygments

install:
 - source ./manuscript/texlive/texlive_install.sh
 
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: 
  - cd $TRAVIS_BUILD_DIR/manuscript
  - chmod +x build.sh
  - mkdir build

script:
  - ./build.sh
  - cd build
  - shopt -s extglob
  - rm !(main.pdf)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: pdf
  local-dir: manuscript/build
  on:
    branch: master

