dist: bionic

language: generic

branches:
  only:
  - master

install:
  - sudo apt-get install texlive texlive-latex-base texlive-latex-extra texlive-bibtex-extra lmodern texlive-fonts-extra biber
 
before_script: 
  - cd $TRAVIS_BUILD_DIR/manuscript
  - chmod +x build.sh
  - mkdir build

script:
  - ./build.sh
  - cd build
  - shopt -s extglob #used to allow the ! expression/command
  - rm !(Main.pdf)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: pdf
  local-dir: manuscript/build
  on:
    branch: master

