language: generic

branches:
  only:
  - master

before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: 
  - cd $TRAVIS_BUILD_DIR
  - chmod +x build.sh

script:
- mkdir build
- ./build.sh
- cd build
- rm main.aux main.log main.out main.spl main.bbl	main.blg


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: submission
  local-dir: build
  on:
    branch: master

